/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moirottoiec.salesmanagement.GUI;

import static java.lang.Integer.parseInt;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import moirottoiec.salesmanagement.BLL.CustomerBLL;
import moirottoiec.salesmanagement.Entity.Customer;

/**
 *
 * @author anhph
 */
public class CustomerGUI_1 extends javax.swing.JPanel {
    
    /**
     * Creates new form CustomerGUI
     */
    
    private CustomerBLL customerBLL;
    private Customer customer;
    String keyword = "";
    DefaultTableModel dtm;
    public CustomerGUI_1() {
        initComponents();
        customer = new Customer();
        customerBLL = new CustomerBLL();
        getCustomerList();
    }
    
    public void getCustomerList(){
        dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        dtm.addColumn("STT");
        dtm.addColumn("Customer ID");
        dtm.addColumn("Full name");
        dtm.addColumn("Phone");
        dtm.addColumn("Address");
        dtm.addColumn("City");
        
        CustomerTable.setModel(dtm);
        
        customerBLL = new CustomerBLL();
        int i = 1;
        for (Iterator iterator = customerBLL.getListCustomer().iterator(); iterator.hasNext();) {
            Customer customer = (Customer) iterator.next();
            Object[] row = {i++, customer.getCustomerID(), customer.getFullName() , customer.getPhone(), customer.getAddress(), customer.getCity()};
            dtm.addRow(row);
                
        } 
       
        AddButton.setEnabled(true);
    }
    
    public void search(){
        dtm.setRowCount(0);
        customerBLL = new CustomerBLL();
        int i = 1;
        for(Iterator iterator = customerBLL.search(keyword).iterator(); iterator.hasNext();){
            Customer customer = (Customer) iterator.next();
            Object[] row = {i++, customer.getCustomerID(), customer.getFullName() , customer.getPhone(), customer.getAddress(), customer.getCity()};
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CustomerIDTextField = new javax.swing.JTextField();
        FullNameTextField = new javax.swing.JTextField();
        PhoneTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        CityTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/salesmanagement/GUI/img/user.png"))); // NOI18N
        jLabel1.setText("CUSTOMER MANAGEMENT");

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Customer ID", "Full name", "Phone", "Address", "City"
            }
        ));
        CustomerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Customer ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Full name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Phone");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("City");

        CustomerIDTextField.setEditable(false);

        PhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneTextFieldActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 51, 51));
        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/salesmanagement/GUI/img/plus.png"))); // NOI18N
        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 51, 51));
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/salesmanagement/GUI/img/update.png"))); // NOI18N
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setForeground(new java.awt.Color(255, 51, 51));
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/salesmanagement/GUI/img/delete.png"))); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        RefreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RefreshButton.setForeground(new java.awt.Color(255, 51, 51));
        RefreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moirottoiec/salesmanagement/GUI/img/refresh.png"))); // NOI18N
        RefreshButton.setText("REFRESH");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        searchTextField.setText("Searching...");
        searchTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTextFieldMouseClicked(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(FullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(CustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(69, 69, 69)
                                        .addComponent(UpdateButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(RefreshButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(391, 391, 391)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddressTextField, CityTextField, CustomerIDTextField, FullNameTextField, PhoneTextField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddButton, DeleteButton, RefreshButton, UpdateButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(CustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(FullNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteButton)
                        .addComponent(RefreshButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddressTextField, CityTextField, CustomerIDTextField, FullNameTextField, PhoneTextField});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddButton, DeleteButton, RefreshButton, UpdateButton});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {searchButton, searchTextField});

    }// </editor-fold>//GEN-END:initComponents

    private void PhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneTextFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String fullName = FullNameTextField.getText();
        String phone = PhoneTextField.getText();
        String address = AddressTextField.getText();
        String city = CityTextField.getText();
        
        
        if(fullName.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ten!");
        }
        else if(phone.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên!");
        }
        else if(address.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập dia chi!");
        }
        else if(city.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập thanh pho!");
        }
        else{
            customer.setFullName(fullName);
            customer.setPhone(parseInt(phone));
            customer.setAddress(address);
            customer.setCity(city);
            
            customerBLL.addCustomer(customer);
            JOptionPane.showMessageDialog(this, "Thêm khách hàng thành công!");
            getCustomerList();
            FullNameTextField.setText("");
            PhoneTextField.setText("");
            AddressTextField.setText("");
            CityTextField.setText("");
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        CustomerBLL cusBLL = new CustomerBLL();
        Customer cus = new Customer();
        int row = CustomerTable.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(CustomerGUI_1.this, "Vui long chon giang vien can xoa!", "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(CustomerGUI_1.this, "Ban chac chan muon xoa chu?");
            if(confirm == JOptionPane.YES_OPTION){

                cus.setCustomerID((int) CustomerTable.getValueAt(row, 1));
                cus.setFullName((String) CustomerTable.getValueAt(row, 2));
                cus.setPhone((int) CustomerTable.getValueAt(row, 3));
                cus.setAddress((String) CustomerTable.getValueAt(row, 4));
                cus.setCity((String) CustomerTable.getValueAt(row, 5));
                cusBLL.deleteCustomer(cus);
                CustomerIDTextField.setText("");
                FullNameTextField.setText("");
                PhoneTextField.setText("");
                AddressTextField.setText("");
                CityTextField.setText("");
                getCustomerList();
            }
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        CustomerBLL cusBLL = new CustomerBLL();
        Customer cus = new Customer();
        int row = CustomerTable.getSelectedRow();
        if (row == -1){
            JOptionPane.showMessageDialog(CustomerGUI_1.this, "Vui long chon giang vien can sua!",  "Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int customerID = (int) CustomerTable.getValueAt(row, 1);
        
            cus.setCustomerID(customerID);
            cus.setFullName(FullNameTextField.getText());
            cus.setPhone(parseInt(PhoneTextField.getText()));
            cus.setAddress(AddressTextField.getText());
            cus.setCity(CityTextField.getText());
            cusBLL.updateCustomer(cus);
            CustomerIDTextField.setText("");
            FullNameTextField.setText("");
            PhoneTextField.setText("");
            AddressTextField.setText("");
            CityTextField.setText("");
            getCustomerList();
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        // TODO add your handling code here:
                Customer cus = new Customer();
        int row = CustomerTable.getSelectedRow();
//                            cus.setCustomerID((int) CustomerTable.getValueAt(row, 1));
//                cus.setFullName((String) CustomerTable.getValueAt(row, 2));
//                cus.setPhone((int) CustomerTable.getValueAt(row, 3));
//                cus.setAddress((String) CustomerTable.getValueAt(row, 4));
//                cus.setCity((String) CustomerTable.getValueAt(row, 5));
                CustomerIDTextField.setText(String.valueOf(CustomerTable.getValueAt(row, 1)));
                FullNameTextField.setText((String) CustomerTable.getValueAt(row, 2));
                PhoneTextField.setText(String.valueOf(CustomerTable.getValueAt(row, 3)));
                AddressTextField.setText((String) CustomerTable.getValueAt(row, 4));
                CityTextField.setText((String) CustomerTable.getValueAt(row, 5));
                AddButton.setEnabled(false);
        
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        CustomerIDTextField.setText("");
        FullNameTextField.setText("");
        PhoneTextField.setText("");
        AddressTextField.setText("");
        CityTextField.setText("");
        searchTextField.setText("Searching...");
        getCustomerList();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        keyword = searchTextField.getText();
        search();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTextFieldMouseClicked
        // TODO add your handling code here:
        searchTextField.setText("");
    }//GEN-LAST:event_searchTextFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField CityTextField;
    private javax.swing.JTextField CustomerIDTextField;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField FullNameTextField;
    private javax.swing.JTextField PhoneTextField;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
